### ISSUE TITLE
해당 프로그램 활용 관련 문의

### ISSUE THREAD

**Issue by kwan2** [omins/notiScrapper#1]
안녕하세요.

동국대학교 컴퓨터공학과 학부생입니다.

학교 수업 '오픈소스소프트웨어프로젝트'에서 해당 notiScrapper 프로그램을 활용 허가 관련 문의드립니다.

허가를 해주신다면, 학교 통합 관리 시스템의 주제에서 활용할 계획이며 MIT 라이선스로 배포할 예정입니다.

허가해주시면 감사하겠습니다 😀

**Comment by omins** [comment]
안녕하세요, 확인이 많이 늦어서 죄송합니다. 관심 가져주셔서 감사합니다 :) 필요하다면 언제든지 사용해주세요!
